services:
  mongodb:
    image: mongo:5.0.27

    container_name: mongodb
    
    ports:
      - "27007:27017"

    volumes:
      - ./mongodb:/data/db

    networks:
      - backend

    restart: always

  networks:
    backend: